/**
 * Lucide component name → Material Symbols icon name
 * Reference: https://fonts.google.com/icons?icon.set=Material+Symbols
 */
export const iconMap: Record<string, string> = {
  // Navigation
  LayoutDashboard: 'grid_view',
  BookOpen: 'auto_stories',
  RotateCcw: 'history_edu',
  User: 'person',
  Search: 'search',
  X: 'close',
  ChevronLeft: 'chevron_left',
  ChevronRight: 'chevron_right',
  ChevronUp: 'expand_less',
  ChevronDown: 'expand_more',
  ArrowRight: 'arrow_forward',
  ArrowLeft: 'arrow_back',
  ExternalLink: 'open_in_new',
  Menu: 'menu',

  // Content & Learning
  Brain: 'psychology',
  Target: 'my_location',
  Zap: 'bolt',
  Sparkles: 'auto_awesome',
  Star: 'bookmark',
  Heart: 'favorite',
  Flame: 'local_fire_department',
  Trophy: 'emoji_events',
  BookMarked: 'bookmark',
  Play: 'play_arrow',
  Pause: 'pause',

  // Status
  CheckCircle2: 'check_circle',
  CheckCircle: 'check_circle',
  Check: 'check',
  Clock: 'schedule',
  Lock: 'lock',
  Unlock: 'lock_open',
  Eye: 'visibility',
  EyeOff: 'visibility_off',

  // Gamification
  Medal: 'military_tech',
  Crown: 'workspace_premium',
  Gem: 'diamond',
  Award: 'military_tech',
  Gift: 'redeem',

  // Settings & System
  Settings: 'settings',
  Bell: 'notifications',
  Sun: 'light_mode',
  Moon: 'dark_mode',
  Monitor: 'desktop_windows',
  Smartphone: 'smartphone',
  Wifi: 'wifi',
  WifiOff: 'wifi_off',
  Volume2: 'volume_up',
  VolumeX: 'volume_off',

  // Actions
  Share2: 'share',
  Share: 'share',
  Download: 'download',
  Upload: 'upload',
  Copy: 'content_copy',
  Trash: 'delete',
  Trash2: 'delete',
  Edit: 'edit',
  Plus: 'add',
  Minus: 'remove',
  RefreshCw: 'refresh',
  MoreHorizontal: 'more_horiz',
  MoreVertical: 'more_vert',
  Filter: 'filter_list',
  SortAsc: 'sort',

  // Alerts
  AlertCircle: 'error',
  AlertTriangle: 'warning',
  Info: 'info',
  HelpCircle: 'help',

  // Module/category visual icons
  Compass: 'explore',
  Lightbulb: 'lightbulb',
  Microscope: 'biotech',
  Rocket: 'rocket_launch',
  FlaskConical: 'science',
  FileText: 'description',
  Layers: 'layers',
  TrendingUp: 'trending_up',
  BarChart: 'bar_chart',
  PieChart: 'pie_chart',
  Activity: 'monitoring',
  Globe: 'public',
  Map: 'map',
  Palette: 'palette',
  Music: 'music_note',
  Code: 'code',
  Terminal: 'terminal',
  Database: 'storage',
  Shield: 'shield',
  Key: 'key',
  Users: 'group',
  MessageSquare: 'chat',
  Mail: 'mail',
  Phone: 'phone',
  Camera: 'photo_camera',
  Image: 'image',
  Film: 'movie',
  Headphones: 'headphones',
  Mic: 'mic',
  Bookmark: 'bookmark',
  Tag: 'label',
  Hash: 'tag',
  AtSign: 'alternate_email',
  Link: 'link',
  Paperclip: 'attach_file',
  Scissors: 'content_cut',
  Type: 'text_fields',
  Bold: 'format_bold',
  Italic: 'format_italic',
  List: 'format_list_bulleted',
  Grid: 'grid_view',
  Layout: 'dashboard',
  Sidebar: 'side_navigation',
  Columns: 'view_column',
  Maximize: 'fullscreen',
  Minimize: 'fullscreen_exit',
  LogOut: 'logout',
  LogIn: 'login',
  UserPlus: 'person_add',
  UserMinus: 'person_remove',

  // Special Polymind icons
  Cpu: 'memory',
  Dumbbell: 'fitness_center',
  Leaf: 'eco',
  Sword: 'swords',
  Scroll: 'history_edu',
  BookHeart: 'menu_book',
  GraduationCap: 'school',
  Infinity: 'all_inclusive',
};
