import type { PathwayLesson } from "@/types";

export const earthLessonsLevel1: PathwayLesson[] = [
  {
    id: "earth-001",
    title: "Welcome to Planet Earth",
    type: "intro",
    duration: 10,
    xpReward: 100,
    content: {
      overview: "Discover how our dynamic planet works as an integrated system of rock, water, air, and life.",
      mainContent: `## The Only Home We Have Ever Known

You are standing on a sphere of rock, metal, and water hurtling through space at 30 kilometers per second. Beneath your feet, tectonic plates drift across a molten mantle. Above you, an impossibly thin atmosphere shields you from deadly radiation. You live on the surface of a dynamic, ever-changing planet — and Earth science is the study of how it all works.

**Earth is 4.54 billion years old.** For perspective, if Earth's history were compressed into a single 24-hour day, humans would appear at 11:59:58 PM — just two seconds before midnight. Dinosaurs would arrive at 11:00 PM. Life itself began around 4:00 AM. Most of Earth's story happened without us.

Our planet is a complex, interconnected system. The **geosphere** (rocks and minerals) interacts with the **hydrosphere** (water), **atmosphere** (air), and **biosphere** (life). Changes in one system cascade through others. When India collided with Asia 50 million years ago, it did not just create the Himalayas — it altered global weather patterns and ocean currents, affecting life worldwide.

> "The Earth is what we all have in common." — Wendell Berry

**Earth is unique in the solar system.** It has liquid water on its surface, a protective magnetic field generated by its iron core, and plate tectonics that recycle minerals and regulate climate over geological timescales. These features make Earth habitable — and remarkably rare.

The forces shaping Earth operate across vast timescales. Continents drift centimeters per year but can travel thousands of kilometers over millions of years. Mountains rise and erode. Ocean basins open and close. The planet beneath your feet is not static — it is a dynamic engine of geological change.

In this pathway, you will explore plate tectonics, the rock cycle, Earth's climate system, and how these processes have shaped our planet over billions of years. You will understand not just what Earth is, but how it became this way — and how it continues to change.`,
      keyTakeaway: "Earth is a dynamic, integrated system where rocks, water, air, and life interact continuously, shaping the planet over billions of years.",
      actionItem: "Find a rock outside. Hold it and consider: it might contain minerals forged in Earth's mantle, crystals that grew over millions of years, or atoms that once cycled through ancient oceans.",
    },
  },
  {
    id: "earth-002",
    title: "Plate Tectonics: The Engine of Geology",
    type: "concept",
    duration: 12,
    xpReward: 100,
    content: {
      overview: "Understand how Earth's crust is divided into moving plates that create mountains, earthquakes, and ocean basins.",
      mainContent: `## The Theory That Unified Geology

In 1912, German meteorologist Alfred Wegener proposed a radical idea: continents move. He noticed that South America and Africa fit together like puzzle pieces and that identical fossil species appeared on both continents. The scientific community mocked him. They asked: what force could possibly move entire continents?

Wegener was right. The theory of **plate tectonics**, fully developed in the 1960s, revolutionized Earth science. It revealed that Earth's outer shell (the lithosphere) is broken into seven major plates and many smaller ones. These plates float on the partially molten asthenosphere beneath them, moving 2-15 centimeters per year — about as fast as your fingernails grow.

**Three types of plate boundaries** define how plates interact:

**Divergent boundaries** occur where plates move apart. Magma rises from the mantle to fill the gap, creating new oceanic crust. The Mid-Atlantic Ridge, a 16,000-kilometer underwater mountain chain, marks where the Eurasian and North American plates separate. Iceland sits atop this ridge, one of the few places where a divergent boundary emerges above sea level.

**Convergent boundaries** form where plates collide. When oceanic crust meets continental crust, the denser oceanic plate subducts (dives) beneath the continent, creating deep ocean trenches and volcanic mountain ranges like the Andes. When two continental plates collide, neither subducts — instead, they crumple upward, forming massive mountain ranges like the Himalayas.

**Transform boundaries** occur where plates slide past each other horizontally. The San Andreas Fault in California is a transform boundary where the Pacific Plate grinds northwest past the North American Plate. This motion stores immense energy, released catastrophically in earthquakes.

> The devastating 2011 Tōhoku earthquake in Japan occurred when the Pacific Plate suddenly lurched beneath the North American Plate, moving the seafloor up to 50 meters. The resulting tsunami killed over 15,000 people.

Plate tectonics explains why earthquakes and volcanoes cluster along plate boundaries, why mountain ranges form where continents collide, and why ocean basins open and close over hundreds of millions of years. It is the grand unifying theory of geology.`,
      keyTakeaway: "Plate tectonics is the fundamental process shaping Earth's surface, driving earthquakes, volcanism, mountain building, and the formation of ocean basins.",
      actionItem: "Visit earthquake.usgs.gov and view real-time earthquake data. Notice how earthquakes cluster along plate boundaries, revealing the invisible architecture of moving plates.",
    },
  },
  {
    id: "earth-003",
    title: "The Rock Cycle: Earth's Recycling System",
    type: "concept",
    duration: 12,
    xpReward: 100,
    content: {
      overview: "Discover how rocks transform from one type to another through geological processes over millions of years.",
      mainContent: `## Nothing Is Permanent

Rocks seem eternal and unchanging. In human timescales, they are. But over geological time, rocks transform continuously through the rock cycle — a system that recycles Earth's crust through heat, pressure, weathering, and melting.

**Igneous rocks** form when molten magma or lava cools and solidifies. Granite, formed from slowly cooling magma deep underground, has large crystals because atoms had time to organize into crystal structures. Basalt, formed from rapidly cooling lava at Earth's surface, has tiny crystals. The ocean floor is predominantly basalt, created at mid-ocean ridges where tectonic plates diverge.

**Sedimentary rocks** form from accumulated sediments — fragments of other rocks, minerals, or organic material. Rivers carry sediment to ocean basins, where it accumulates in layers. Over millions of years, burial compacts the sediment and minerals precipitate between grains, cementing them into solid rock. Limestone forms from accumulated shells of marine organisms. Sandstone forms from ancient beaches and deserts.

**Metamorphic rocks** form when existing rocks are subjected to intense heat and pressure without melting. Limestone transforms into marble. Shale becomes slate, then schist, then gneiss as pressure increases. The atoms rearrange into new crystal structures stable at higher temperatures and pressures. Metamorphic rocks often form in mountain-building zones where tectonic forces compress and heat the crust.

**The cycle has no beginning or end.** Igneous rocks weather into sediment, which becomes sedimentary rock, which may be metamorphosed, which may melt into magma, which crystallizes into new igneous rock. Or the cycle may skip steps: sedimentary rock can melt directly into magma, or igneous rock can be metamorphosed without first becoming sediment.

> The sand on a beach represents rocks in mid-cycle. Those quartz grains may have been part of granite in a mountain range, weathered free over millions of years, and will eventually compact into sandstone, completing their transformation.

**James Hutton**, the 18th-century Scottish geologist, recognized that geological processes operating today have worked throughout Earth's history. He observed layers of sedimentary rock tilted vertically, eroded, and buried under horizontal layers — evidence of multiple cycles of deposition, uplift, erosion, and reburial. He called this "deep time," realizing Earth must be vastly older than anyone imagined.`,
      keyTakeaway: "The rock cycle continuously transforms Earth's crust through weathering, sedimentation, heat, and pressure, recycling materials over millions of years.",
      actionItem: "Examine a piece of granite closely. The different colored crystals (quartz, feldspar, mica) formed at different temperatures as magma slowly cooled deep underground.",
    },
  },
  {
    id: "earth-004",
    title: "Quiz: Plate Tectonics Fundamentals",
    type: "quiz",
    duration: 8,
    xpReward: 100,
    content: {
      overview: "Test your understanding of how Earth's tectonic plates shape the planet.",
      mainContent: `## Knowledge Check

Verify your grasp of plate boundaries and their geological consequences.`,
      keyTakeaway: "Different types of plate boundaries produce characteristic geological features and hazards.",
      quiz: {
        question: "Why do the Himalayas continue to rise at about 5 millimeters per year despite millions of years of erosion?",
        options: [
          "The Indian and Eurasian continental plates continue to collide, compressing and uplifting the crust faster than erosion can wear it down",
          "Volcanic activity beneath the Himalayas adds new material from the mantle",
          "Climate change has reduced erosion rates in the region",
          "The mountains are rebounding from the weight of glaciers that melted thousands of years ago",
        ],
        correct: 0,
        explanation: "The Himalayas formed when the Indian Plate collided with the Eurasian Plate about 50 million years ago. This collision continues today at about 2 centimeters per year. Because both plates are continental crust (which is too buoyant to subduct), they crumple upward instead, continuously adding height faster than erosion can remove it. Mount Everest grows about 4mm taller each year.",
      },
    },
  },
  {
    id: "earth-005",
    title: "Climate: The Long View",
    type: "concept",
    duration: 12,
    xpReward: 100,
    content: {
      overview: "Explore how Earth's climate has changed over geological time and what drives these transformations.",
      mainContent: `## A Planet of Extremes

Earth's climate has varied dramatically over its 4.5-billion-year history. There have been periods when the entire planet was frozen into a "snowball Earth" and others when palm trees grew at the poles. Understanding past climates reveals the natural variability of Earth's systems — and makes current human-caused climate change even more striking by contrast.

**Ice cores from Antarctica and Greenland** preserve atmospheric samples trapped in ice for 800,000 years. By analyzing air bubbles, scientists can measure ancient CO₂ levels and temperatures. The data reveals a clear pattern: CO₂ and temperature rise and fall together, driven by orbital variations in Earth's path around the Sun (Milankovitch cycles).

Over the past million years, Earth has cycled between ice ages (glacial periods) and warm periods (interglacials) every 100,000 years. During the last ice age's peak 20,000 years ago, ice sheets covered Canada, northern Europe, and parts of Asia. Sea level was 120 meters lower than today because so much water was locked in ice. The English Channel did not exist — you could walk from France to Britain.

**Atmospheric CO₂ has varied between 180 ppm (parts per million) during ice ages and 280 ppm during warm periods.** These variations drove temperature changes of 4-7°C globally. However, current CO₂ levels exceed 420 ppm — 50% higher than any point in the past 800,000 years — due to human fossil fuel burning.

**Tectonic processes regulate climate over millions of years.** When India collided with Asia, it exposed vast amounts of fresh rock. Chemical weathering of this rock removed CO₂ from the atmosphere, contributing to global cooling and the ice ages of the past few million years. Volcanic eruptions release CO₂, warming the planet over geological timescales.

> The Paleocene-Eocene Thermal Maximum, 56 million years ago, saw global temperatures spike 5-8°C over a few thousand years as massive carbon reservoirs released into the atmosphere. Deep ocean life suffered mass extinction. It took Earth 100,000 years to recover.

**Earth's climate system involves complex feedbacks.** Ice reflects sunlight, cooling the planet — but as ice melts, darker ocean and land absorb more heat, accelerating warming (positive feedback). Clouds can both reflect sunlight and trap heat. Changing ocean currents redistribute heat globally. These interactions make climate prediction challenging but do not change the fundamental physics: more greenhouse gases mean higher temperatures.`,
      keyTakeaway: "Earth's climate has varied dramatically over geological time due to orbital changes, tectonic processes, and atmospheric composition — but current CO₂ levels are unprecedented in human history.",
      actionItem: "Visit climate.nasa.gov to explore evidence of climate change. Compare current CO₂ levels (420+ ppm) to the natural range of the past 800,000 years (180-280 ppm).",
    },
  },
  {
    id: "earth-006",
    title: "Quiz: The Rock Cycle",
    type: "quiz",
    duration: 8,
    xpReward: 100,
    content: {
      overview: "Test your knowledge of how rocks transform through geological processes.",
      mainContent: `## Knowledge Check

Assess your understanding of the rock cycle and rock formation.`,
      keyTakeaway: "Rocks continuously transform from one type to another through heat, pressure, weathering, and melting.",
      quiz: {
        question: "What evidence would indicate that a metamorphic rock like gneiss was once buried deep in Earth's crust?",
        options: [
          "The presence of minerals like garnet that only form under high pressure and temperature conditions deep underground",
          "Layers of sediment compressed into the rock",
          "Crystals formed from slowly cooling magma",
          "Fossils preserved within the rock structure",
        ],
        correct: 0,
        explanation: "Certain minerals called index minerals form only under specific temperature and pressure conditions. Garnet, for example, forms only at pressures corresponding to depths of 15-25 kilometers below Earth's surface. Finding garnet in gneiss tells geologists the rock was once buried that deep before being uplifted and exposed at the surface through tectonic processes.",
      },
    },
  },
  {
    id: "earth-007",
    title: "Earth's Water: The Hydrological Cycle",
    type: "concept",
    duration: 12,
    xpReward: 100,
    content: {
      overview: "Understand how water moves between the ocean, atmosphere, land, and living things in a continuous cycle.",
      mainContent: `## The Water You Drink Is Older Than the Sun

Every drop of water on Earth has cycled through the hydrological system countless times. The water in your glass might have fallen as rain on the Amazon rainforest, flowed through dinosaur kidneys, frozen in Antarctic ice, or existed as vapor in ancient clouds. Water is neither created nor destroyed — it cycles endlessly.

**Earth contains about 1.386 billion cubic kilometers of water.** Of this, 97.5% is saltwater in the oceans. Of the remaining 2.5% freshwater, 68.7% is frozen in ice caps and glaciers, mostly in Antarctica and Greenland. Less than 1% of Earth's water is accessible freshwater in lakes, rivers, and groundwater that humans can readily use.

**The hydrological cycle** is powered by solar energy. Sunlight evaporates water from oceans, lakes, and soil. Plants transpire water from their leaves. Water vapor rises and cools, condensing into clouds. When droplets grow large enough, they fall as precipitation — rain, snow, or hail.

Precipitation that falls on land takes several paths. Some evaporates back into the atmosphere. Some is absorbed by plants and transpired. Some infiltrates soil, recharging underground aquifers. The rest flows over the surface as runoff, eventually reaching streams, rivers, and ultimately the ocean, where the cycle continues.

**Residence time** varies dramatically. Water spends an average of 9 days in the atmosphere before falling as precipitation. It remains in rivers for about 16 days, in lakes for years to decades, and in groundwater for 100 to 10,000 years. The deepest groundwater can be millions of years old — truly ancient water.

> The Antarctic ice sheet contains ice up to 800,000 years old. Some groundwater in ancient aquifers has been isolated from the surface for over a million years, preserving chemistry from a different geological era.

**Humans have significantly altered the water cycle.** We have built 58,000 large dams, fragmenting rivers. We have drained wetlands and withdrawn groundwater faster than it recharges. We have paved surfaces, increasing runoff and reducing infiltration. Climate change is intensifying the cycle, leading to more extreme droughts and floods.

Water is the universal solvent, shaping Earth's surface through erosion and dissolution. Rivers carve canyons. Groundwater dissolves limestone, creating caves. Glaciers scour valleys. Water is geology's most powerful sculptor.`,
      keyTakeaway: "Water cycles continuously through Earth's systems, driven by solar energy, shaping landscapes and sustaining life while spending vastly different times in different reservoirs.",
      actionItem: "Check where your drinking water comes from. Is it from a river, lake, or groundwater aquifer? How long has it been cycling through the hydrological system before reaching you?",
    },
  },
  {
    id: "earth-008",
    title: "Quiz: Climate and Earth Systems",
    type: "quiz",
    duration: 8,
    xpReward: 100,
    content: {
      overview: "Test your understanding of Earth's climate system and its changes over time.",
      mainContent: `## Knowledge Check

Verify your grasp of the factors driving Earth's climate across different timescales.`,
      keyTakeaway: "Multiple factors operate on different timescales to regulate Earth's climate, from orbital variations to atmospheric composition.",
      quiz: {
        question: "Why is the current rate of atmospheric CO₂ increase more concerning than higher CO₂ levels that existed millions of years ago?",
        options: [
          "The rate of change is unprecedented in geological history — rising 50% in just 200 years, giving ecosystems no time to adapt",
          "Ancient CO₂ was natural while current CO₂ is human-made, making it chemically different",
          "Previous high CO₂ periods did not affect global temperatures",
          "Modern measurement techniques are more accurate than geological proxies",
        ],
        correct: 0,
        explanation: "While Earth has had higher CO₂ levels in the distant past, those changes occurred over millions of years, allowing life to adapt gradually. Current CO₂ has increased from 280 to 420+ ppm in just 200 years — a rate of change faster than almost anything in the geological record. Ecosystems, agriculture, and human infrastructure adapted to relatively stable climate conditions cannot adjust this quickly. The speed of change, not just the magnitude, is what makes current climate change so disruptive.",
      },
    },
  },
];
